services:
  auth-db:
    image: postgres:16
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: urr_user
      POSTGRES_PASSWORD: urr_password
    ports:
      - "5438:5432"

  ticket-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ticket_db
      POSTGRES_USER: urr_user
      POSTGRES_PASSWORD: urr_password
    ports:
      - "5434:5432"

  payment-db:
    image: postgres:16
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: urr_user
      POSTGRES_PASSWORD: urr_password
    ports:
      - "5435:5432"

  stats-db:
    image: postgres:16
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: urr_user
      POSTGRES_PASSWORD: urr_password
    ports:
      - "5436:5432"

  community-db:
    image: postgres:16
    environment:
      POSTGRES_DB: community_db
      POSTGRES_USER: urr_user
      POSTGRES_PASSWORD: urr_password
    ports:
      - "5437:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  zipkin:
    image: openzipkin/zipkin:3
    ports:
      - "9411:9411"

  prometheus:
    image: prom/prometheus:v2.51.0
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.4.0
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3200:3000"
    depends_on:
      - prometheus

  kafka:
    image: apache/kafka:3.6.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    ports:
      - "9092:9092"
