services:
  auth-db:
    image: postgres:16
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: tiketi_user
      POSTGRES_PASSWORD: tiketi_password
    ports:
      - "5433:5432"

  ticket-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ticket_db
      POSTGRES_USER: tiketi_user
      POSTGRES_PASSWORD: tiketi_password
    ports:
      - "5434:5432"

  payment-db:
    image: postgres:16
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: tiketi_user
      POSTGRES_PASSWORD: tiketi_password
    ports:
      - "5435:5432"

  stats-db:
    image: postgres:16
    environment:
      POSTGRES_DB: stats_db
      POSTGRES_USER: tiketi_user
      POSTGRES_PASSWORD: tiketi_password
    ports:
      - "5436:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
