apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z postgres-spring 5432; do echo waiting for postgres; sleep 2; done
      containers:
        - name: auth-service
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: spring-kind-config
            - secretRef:
                name: spring-kind-secret
          env:
            - name: PORT
              value: "3005"
            - name: SPRING_PROFILES_ACTIVE
              value: "kind"
            - name: AUTH_DB_URL
              value: "jdbc:postgresql://postgres-spring:5432/auth_db"
            - name: ZIPKIN_ENDPOINT
              value: "http://zipkin-spring:9411/api/v2/spans"
            - name: COOKIE_SECURE
              value: "false"
