apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-deps
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              check() { until nc -z $1 $2; do sleep 1; done; }
              check postgres-spring 5432 &
              check kafka-spring 9092 &
              wait
      containers:
        - name: payment-service
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: spring-kind-config
            - secretRef:
                name: spring-kind-secret
          env:
            - name: PORT
              value: "3003"
            - name: SPRING_PROFILES_ACTIVE
              value: "kind"
            - name: PAYMENT_DB_URL
              value: "jdbc:postgresql://postgres-spring:5432/payment_db"
            - name: TICKET_SERVICE_URL
              value: "http://ticket-service:3002"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-spring:9092"
            - name: ZIPKIN_ENDPOINT
              value: "http://zipkin-spring:9411/api/v2/spans"
