apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-service
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z dragonfly-spring 6379; do echo waiting for redis; sleep 2; done
      containers:
        - name: queue-service
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: spring-kind-config
            - secretRef:
                name: spring-kind-secret
          env:
            - name: PORT
              value: "3007"
            - name: SPRING_PROFILES_ACTIVE
              value: "kind"
            - name: TICKET_SERVICE_URL
              value: "http://ticket-service:3002"
            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service:3009"
            - name: REDIS_HOST
              value: "dragonfly-spring"
            - name: REDIS_PORT
              value: "6379"
            - name: ZIPKIN_ENDPOINT
              value: "http://zipkin-spring:9411/api/v2/spans"
            - name: SQS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: spring-kind-config
                  key: SQS_ENABLED
            - name: SQS_QUEUE_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-kind-config
                  key: SQS_QUEUE_URL
