apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z postgres-spring 5432; do echo waiting for postgres; sleep 2; done
        - name: wait-for-redis
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z dragonfly-spring 6379; do echo waiting for redis; sleep 2; done
        - name: wait-for-kafka
          image: busybox:1.36
          command:
            - sh
            - -c
            - until nc -z kafka-spring 9092; do echo waiting for kafka; sleep 2; done
      containers:
        - name: ticket-service
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: spring-kind-config
            - secretRef:
                name: spring-kind-secret
          env:
            - name: PORT
              value: "3002"
            - name: SPRING_PROFILES_ACTIVE
              value: "kind"
            - name: TICKET_DB_URL
              value: "jdbc:postgresql://postgres-spring:5432/ticket_db"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service:3005"
            - name: REDIS_HOST
              value: "dragonfly-spring"
            - name: REDIS_PORT
              value: "6379"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-spring:9092"
            - name: ZIPKIN_ENDPOINT
              value: "http://zipkin-spring:9411/api/v2/spans"
