apiVersion: v1
kind: Service
metadata:
  name: community-service
  labels:
    app: community-service
spec:
  selector:
    app: community-service
  ports:
    - protocol: TCP
      port: 3008
      targetPort: 3008
