apiVersion: v1
kind: Service
metadata:
  name: queue-service
  labels:
    app: queue-service
spec:
  selector:
    app: queue-service
  ports:
    - protocol: TCP
      port: 3007
      targetPort: 3007
