global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:3001']

  - job_name: 'ticket-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:3002']

  - job_name: 'payment-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:3003']

  - job_name: 'stats-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:3004']

  - job_name: 'auth-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:3005']

  - job_name: 'queue-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:3007']

  - job_name: 'community-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:3008']

  - job_name: 'catalog-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:3009']
